### ISSUE TITLE
Creating the Github Repository for the R Dashboard

### ISSUE THREAD

**Issue by Anahita97** [UBC-MDS/netflixpy_dashboard-R#1]
- Create a new github.com repo and Name it the same as your Python dashboard repo plus a -R suffix.
- Copy over your contributing guidelines, the code of conduct, license, the README file, and the necessary data files.

**Comment by Anahita97** [comment]
How about we change the name of this repo to netflix_dashboard-R and name our Python repo netflix_dashboard-py?

**Comment by rrrohit1** [comment]
I'm a little worried that a lot of the links would have to be changed now. So, we will leave it as it is for now.
